### PR TITLE
commented out frequency setting 

### PR DESCRIPTION
**Pull request by newkit**
since its only needed for live migration and HW dependent

### CODE REVIEW

**Comment by Klaas-** [comment]
isn't the goal to also be able to live migrate hana VMs?

**Comment by newkit** [comment]
Yes, you are correct @Klaas- . But since this requires setting the frequency to a specific value that suits the CPU type in your cluster there is no general setting. Therefore it's safer to have it commented out before a user sets a potential wrong setting on his environment without even knowing. This way, it requires active activation by the user.

**Comment by Klaas-** [comment]
maybe I'm missing something but my understanding was that with 4.3 I can live migrate high performance VMs -- will using the hana hook keep me from doing that as long as I don't set the frequency setting?

**Comment by newkit** [comment]
IIRC 4.3 will handle the TSC frequency setting itself. This hook is mainly for 4.2. Not sure though if the other CPU flags (invtsc, x2apic) are set now through RHV with 4.3.

**Pull request merged**
